.datatable.aware = TRUE
#for NSE R CMD check; data.table vars
utils::globalVariables(
  c("."
    , "..cols.merge"
    , "..cols_thaw"
    , "..drop.cols"
    , ".I"
    , ".N"
    , ":="
    , "batch.order"
    , "batch.seq"
    , "block"
    , "box.id"
    , "box.label"
    , "box.row.col"
    , "box.row.cols"
    , "cells.per.condition"
    , "concentration.live"
    , "freezer"
    , "g.id"
    , "g.ids"
    , "N"
    , "N.conditions"
    , "N.plates"
    , "position.in.row"
    , "rack.location"
    , "resuspension.volume.ul"
    , "row.id"
    , "row_col"
    , "sample.id"
    , "sample.name"
    , "stage.name"
    , "stage.position"
    , "stim.id"
    , "study.id"
    , "study.name"
    , "subject.id"
    , "subject.id.alias"
    , "total.live"
    , "tube.label"
    , "visit"
    , "visit.alias"
    , "visit.id"
    , "volume.ml"
    , "wells"
  )
)
